### ISSUE TITLE
Jakarta REST 4.0 Epic

### ISSUE THREAD

**Issue by jim-krueger** [jakartaee/rest#1233]
The work for this proposal will be carried out in the `main` branch.

**General**

- [x] Clean pom files, use dependency and plugin management, verify all versions 
- [x] Drop dependency with JAXB [Issue1226](https://github.com/jakartaee/rest/issues/1226)
- [x] Update README, LICENSE and review all other top-level files
- [ ] Review copyrights and licenses in all files (especially pom files)

**API**

- [ ] Convenience method for checking header value lists: [PR #1066](https://github.com/jakartaee/rest/pull/1066 )

**Specification**

- [ ] Remove @ManagedBean [Issue 1216](https://github.com/jakartaee/rest/issues/1216)
- [ ] Clarify JavaSE support in Section 2.3 of specification [Issue #1127](https://github.com/jakartaee/rest/issues/1127) 

**Examples**

- [ ] Remove any examples that are not longer relevant

**TCKs**

- [ ] Port all TCK tests to run with new 4.0 API
- [ ] New TCK tests for Multipart: [Issue 962](https://github.com/jakartaee/rest/issues/962)
- [ ] New TCK tests for header value checking convenience feature: [Issue 1227](https://github.com/jakartaee/rest/issues/1227) 
- [ ] New TCK tests for default ExceptionMapper: [Issue 1188](https://github.com/jakartaee/rest/issues/1188)

**Comment by mkarg** [comment]
Why not closing this issue?
